# Generated by Django 4.2 on 2025-09-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_audioauthor_audiocategory_audiobook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiobook',
            options={'ordering': ('title', 'author', 'description')},
        ),
    ]
